services:
  mus-postgresql:
    image: postgres:17.0
    container_name: ${PROJECT_SHORT_NAME}-postgres
    command: [ "postgres", "-c", "config_file=/etc/postgres/conf.d/postgresql.conf" ]
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - mus_postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/postgres/postgresql.conf:/etc/postgres/conf.d/postgresql.conf

volumes:
  mus_postgres_data:
